# https://github.com/actions/dependency-review-action/tree/v4/?tab=readme-ov-file#configuration-file

# Comment summary in PR
comment-summary-in-pr: "always"

# Set the severity level for the action to fail on.
fail-on-severity: moderate

# Set what scope to fail on.
fail-on-scopes: runtime

# Here is the list of licenses we want to deny and not use in our software. 
deny-licenses:
  # GPL licenses
  - GPL-1.0-only
  - GPL-1.0-or-later
  - GPL-2.0-only
  - GPL-2.0-or-later
  - GPL-3.0-only
  - GPL-3.0-or-later
  # AGPL licenses
  - AGPL-1.0-only
  - AGPL-1.0-or-later
  - AGPL-3.0-only
  - AGPL-3.0-or-later
  # LGPL licenses
  - LGPL-2.0-only
  - LGPL-2.0-or-later
  - LGPL-2.1-only
  - LGPL-2.1-or-later
  - LGPL-3.0-only
  - LGPL-3.0-or-later
