name: Language Detection and Assignment

on:
  pull_request:
    branches: [main]

jobs:
  detect-and-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed files' languages
        id: detect-languages
        uses: dorny/paths-filter@v2
        with:
          list-files: json
          filters: |
            java:
              - '**/*.java'
            kotlin:
              - '**/*.kt'
            javascript:
              - '**/*.js'
            typescript:
              - '**/*.ts'
            go:
              - '**/*.go'
            python:
              - '**/*.py'
            rust:
              - '**/*.rs'
            codeql:
              - '**/*.ql'
              - '**/*.qll'

      - name: Assign for Java, Kotlin, JavaScript, TypeScript, Go
        if: steps.detect-languages.outputs.java == 'true' || steps.detect-languages.outputs.kotlin == 'true' || steps.detect-languages.outputs.javascript == 'true' || steps.detect-languages.outputs.typescript == 'true' || steps.detect-languages.outputs.go == 'true'
        uses: peter-evans/assign@v1
        with:
          users: adrienpessu

      - name: Assign for Python, Go, CodeQL, Rust
        if: steps.detect-languages.outputs.python == 'true' || steps.detect-languages.outputs.go == 'true' || steps.detect-languages.outputs.codeql == 'true' || steps.detect-languages.outputs.rust == 'true'
        uses: peter-evans/assign@v1
        with:
          users: Geekmasher

      - name: Assign for Python, JavaScript, TypeScript, CodeQL
        if: steps.detect-languages.outputs.python == 'true' || steps.detect-languages.outputs.javascript == 'true' || steps.detect-languages.outputs.typescript == 'true' || steps.detect-languages.outputs.codeql == 'true'
        uses: peter-evans/assign@v1
        with:
          users: felickz

      - name: Assign for Java, Kotlin, JavaScript, TypeScript, Go
        if: steps.detect-languages.outputs.java != 'true' && steps.detect-languages.outputs.kotlin != 'true' && steps.detect-languages.outputs.javascript != 'true' && steps.detect-languages.outputs.typescript != 'true' && steps.detect-languages.outputs.go != 'true'  && steps.detect-languages.outputs.codeql != 'true' && steps.detect-languages.outputs.python != 'true'  
        uses: peter-evans/assign@v1
        with:
          users: oss-maintainers
