name: 'Dependency Review'

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Check for configuration file'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e
          if [ -f "./.github/dependency-review.yml" ]; then
            echo "Found local configuration file"
          else
            echo "No local configuration file found"
            echo "Downloading configuration file from advanced-security/reusable-workflows repository"

            # download file using gh cli
            gh api repos/advanced-security/reusable-workflows/contents/.github/dependency-review.yml -q '.content' | base64 -d > .github/dependency-review.yml

          fi

      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          config-file: './.github/dependency-review.yml'
          comment-summary-in-pr: "always"
