name: Labeler

on:
  workflow_call:
    inputs:
      version:
        description: 'The version of the labeler action to use'
        required: true
        type: string
        default: 'v5'
    secrets:
      token:
        required: true

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: "actions/labeler@${{ github.event.inputs.version }}"
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
