name: Labeler

on:
  workflow_call:
    inputs:
      configuration-path:
        description: "Path to the labeler configuration file"
        required: false
        type: string
        default: ".github/labeler.yml"

permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Check if the .github/labeler.yml file exists
    - name: Check for labeler configuration
      id: labeler-config
      run: |
        if [ -f .github/labeler.yml ]; then
          echo "Labeler configuration found"
          echo "config=./.github/labeler.yml" >> $GITHUB_STATE

        elif [[ -f "${{ github.event.inputs.configuration-path }}" ]]; then
          echo "Labeler configuration found"
          echo "config=${{ github.event.inputs.configuration-path }}" >> $GITHUB_STATE

        else
          echo "No local labeler configuration found"
          echo "Using default configuration"
          # Get configuration from current action repository

          cat >${{ github.event.inputs.configuration-path }} <<EOL
          docs:
          - changed-files:
            - any-glob-to-any-file: 'docs/*'

          actions:
          - changed-files:
            - any-glob-to-any-file: '.github/workflows/*'
          EOL

        fi

    - uses: "actions/labeler@v5"
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: "${{ steps.labeler-config.outputs.config }}"
        sync-labels: true
